export interface IBaseLangResources {
    "commons": {
        "askForDeleteConfirmation": string,
        "back": string,
        "buy": string,
        "cart": string,
        "create": string,
        "edit": string,
        "details": string,
        "delete": string,
        "home": string,
        "logout": string,
        "login": string,
        "register": string,
        "products": string,
        "save": string,
        "select": string,
        "thanksForOrdering": string,
        "purchase": string,
        "remove": string,
        "shop": string,
        "addToCart": string,
        "view": string,
        "totalPrice": string,
        "productName": string,
        "productAmount": string,
        "price": string,
        "firstName": string,
        "lastName": string,
        "idCode": string
        "person": string,
        "createPerson": string,
        "paymentTypeName": string
    }
}